resources:
- ../../../base/website
patches:
- path: patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: website
- path: patch-B.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: website-b