cluster: eks-infra
env: qa

image:
  tag: qa-2026-01-11T21.12.21Z # deploy: ricardofukuda branch: master commit: 7b0e5f793b00b63540187cdb5335af68de86c7cf

istio:
  gateway:
    public:
      hosts:
        - website.ricardoxyz.website

external_secrets:
  secret_version: qa-2026-01-11T21.12.21Z # eks-infra/qa/website
