cluster: eks-infra
env: qa

image:
  tag: qa-2026-01-28T21.15.04Z # deploy by @ricardofukuda branch: master commit: e402a2edd42f3a2db22a6905cf4b155f1936f0fb

istio:
  gateway:
    public:
      hosts:
        - website.ricardoxyz.website

external_secrets:
  secret_version: qa-2026-01-28T21.15.04Z # eks-infra/qa/website
