cluster: eks-infra
env: qa

image:
  tag: qa-2026-01-11T21.01.19Z # deploy: ricardofukuda branch: master commit: 43829d6dc2bcc003328c04d26b0f5ee84328b8e6

istio:
  gateway:
    public:
      hosts:
        - website.ricardoxyz.website

external_secrets:
  secret_version: qa-2026-01-11T21.01.19Z # eks-infra/qa/website
