cluster: eks-infra
env: qa

image:
  tag: qa-2026-01-11T21.06.58Z # deploy: ricardofukuda branch: master commit: 89654ef3e544d1aea5bc5ada1c6faa706244e20f

istio:
  gateway:
    public:
      hosts:
        - website.ricardoxyz.website

external_secrets:
  secret_version: qa-2026-01-11T21.06.58Z # eks-infra/qa/website
