cluster: eks-infra
env: qa

image:
  tag: qa-2026-01-18T19.21.22Z # deploy by @ricardofukuda branch: master commit: 763817febe9f0134aa75d633d6f34b88b49e52fd

istio:
  gateway:
    public:
      hosts:
        - website.ricardoxyz.website

external_secrets:
  secret_version: qa-2026-01-18T19.21.22Z # eks-infra/qa/website
