cluster: eks-infra
env: qa

image:
  tag: qa-2026-01-11T21.31.36Z # deploy: ricardofukuda branch: master commit: e973dc760909e8ee25e98ae01f7bb63cb4c733dd

istio:
  gateway:
    public:
      hosts:
        - website.ricardoxyz.website

external_secrets:
  secret_version: qa-2026-01-11T21.31.36Z # eks-infra/qa/website
